name: sample_provider_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.3
  provider_architecture: ^1.1.1+1
  provider: ^4.1.2
  async: ^2.4.0
  get_it: ^4.0.0
  shared_preferences: ^0.5.6+2
  google_fonts: ^0.3.9
  logger: ^0.8.3
  dio: ^3.0.9
  rxdart: ^0.23.1
  permission_handler: ^5.0.0+hotfix.6
  url_launcher: ^5.4.2
  intl: ^0.16.1
  connectivity: ^0.4.8+1
  path_provider: ^1.6.11
  device_id: ^0.2.0
  get_ip: ^0.4.0
  package_info: ^0.4.0+5
  carousel_slider: ^2.0.0
  flutter_rating_bar: ^3.0.1+1
  fluttertoast: ^7.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/i18n/
    - assets/data/


  fonts:
    - family:  FlutterIcon
      fonts:
        - asset: assets/fonts/flutter_icon.ttf

